# Generated by Django 4.0.4 on 2022-05-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='attribute',
        ),
    ]
